// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEfkoUsBBFX7shQallg8ptCEUGvDRHhu4',
    appId: '1:122154039374:web:be5bdd0016946fcaffab1f',
    messagingSenderId: '122154039374',
    projectId: 'librix-8ebc4',
    authDomain: 'librix-8ebc4.firebaseapp.com',
    databaseURL: 'https://librix-8ebc4-default-rtdb.firebaseio.com',
    storageBucket: 'librix-8ebc4.firebasestorage.app',
    measurementId: 'G-ET5X5M2JH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRJTIZGZnNMSMC-gRwpoqRbxFg8heHCU',
    appId: '1:122154039374:android:7a4cad30720d0c12ffab1f',
    messagingSenderId: '122154039374',
    projectId: 'librix-8ebc4',
    databaseURL: 'https://librix-8ebc4-default-rtdb.firebaseio.com',
    storageBucket: 'librix-8ebc4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEfkoUsBBFX7shQallg8ptCEUGvDRHhu4',
    appId: '1:122154039374:web:17a4bbff94a31690ffab1f',
    messagingSenderId: '122154039374',
    projectId: 'librix-8ebc4',
    authDomain: 'librix-8ebc4.firebaseapp.com',
    databaseURL: 'https://librix-8ebc4-default-rtdb.firebaseio.com',
    storageBucket: 'librix-8ebc4.firebasestorage.app',
    measurementId: 'G-GDFRBJCX76',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD946Inlh_loy4ELf9cfrWNjj9iyVhhI_A',
    appId: '1:122154039374:ios:6c648eb582e7cb58ffab1f',
    messagingSenderId: '122154039374',
    projectId: 'librix-8ebc4',
    databaseURL: 'https://librix-8ebc4-default-rtdb.firebaseio.com',
    storageBucket: 'librix-8ebc4.firebasestorage.app',
    iosBundleId: 'com.example.learningapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD946Inlh_loy4ELf9cfrWNjj9iyVhhI_A',
    appId: '1:122154039374:ios:6c648eb582e7cb58ffab1f',
    messagingSenderId: '122154039374',
    projectId: 'librix-8ebc4',
    databaseURL: 'https://librix-8ebc4-default-rtdb.firebaseio.com',
    storageBucket: 'librix-8ebc4.firebasestorage.app',
    iosBundleId: 'com.example.learningapp',
  );

}